CREATE TABLE Orders
(
       ID NUMBER PRIMARY KEY,
       NAME NVARCHAR2(50) NOT NULL,
       ADDRESS NVARCHAR2(200) NOT NULL,
       CREATETIME DATE NULL
);

CREATE TABLE Goods
(
       ID NUMBER PRIMARY KEY,
       PRICE NUMBER(11,2) NULL,
       NAME NVARCHAR2(50) NULL,
       SPECIFICATION NVARCHAR2(2000) NULL,
       MANUFACTURER NVARCHAR2(100) NULL
);

CREATE TABLE Orderitem
(
       ID NUMBER PRIMARY KEY,
       GID NUMBER NOT NULL,
       OID NUMBER NOT NULL,
       AMOUNT NUMBER NOT NULL
);

ALTER TABLE Orderitem
ADD CONSTRAINTS FK_Orders FOREIGN KEY(OID) REFERENCES Orders(ID);
ALTER TABLE Orderitem
ADD CONSTRAINTS FK_Goods FOREIGN KEY(GID) REFERENCES Goods(ID);

